####
# Dockerfile para ejecutar el binario nativo de GraalVM
# Este Dockerfile usa una imagen base minimal para máxima eficiencia
####

FROM ghcr.io/graalvm/jdk-community:21
WORKDIR /work/

COPY target/auth-service-1.0.0-runner /work/application
RUN chmod 775 /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
